name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Restore
      run: dotnet restore ./ProjetoCiCd/ProjetoCiCd.csproj

    - name: Build
      run: dotnet build ./ProjetoCiCd/ProjetoCiCd.csproj

    - name: Publish
      run: dotnet publish ./ProjetoCiCd/ProjetoCiCd.csproj -c Release -o out

    - name: Deploy
      run: echo "Deploy realizado com sucesso 🚀"